events {
    worker_connections 1024;
}

http {
    upstream user_service {
        server user-service:5000;
    }
    upstream order_service {
        server order-service:3000;
    }

    server {
        listen 80;

        # Маршрут для user-service: убираем префикс /api
        location /api/users {
            rewrite ^/api/users(.*)$ /users$1 break;
            proxy_pass http://user_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Маршрут для order-service: убираем префикс /api
        location /api/orders {
            rewrite ^/api/orders(.*)$ /orders$1 break;
            proxy_pass http://order_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Health check шлюза
        location /health {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
}
